### ISSUE TITLE
Security issue with remotedev dependency

### ISSUE THREAD

**Issue by alfonsogarciacaro** [elmish/debugger#12]
When using latest npm to install JS dependencies there's a warning about remote dev that cannot be automatically fixed. See: https://github.com/SAFE-Stack/SAFE-template/issues/113

Unfortunately the issue has been reported a while ago but there's not been a new release in two years: https://github.com/zalmoxisus/remotedev/issues/10

Maybe we need to fork the project and release our own package with updated dependencies. It would be also possible to bundle the JS code and include in the Fable.Elmish.Browser nuget package.

**Comment by et1975** [comment]
Wow, Mikhail seems to have fallen off the face of the earth... 
Since it's not surfaced as a dependency as longs as it implements the bindings forking it is a transparent option from my perspective (and probably a better option overall).

**Comment by alfonsogarciacaro** [comment]
Ok, I forked the project and updated the dependencies here: https://github.com/alfonsogarciacaro/remotedev

I gave it a quick try but the debugger wasn't working quite right. I'll try to investigate further. If you want to give it a try you can:

- Clone https://github.com/alfonsogarciacaro/remotedev
- `cd remotedev && yarn link`
- Go to test project directory and run `yarn link fable-remotedev`
- Add this to your webpack.config.js: +`resolve: { alias: "remotedev": "fable-remotedev" }`

**Comment by alfonsogarciacaro** [comment]
Finally a new version of remotedev has been released so we can close this. However, I'm having some issues to make it work, are the latest versions of remotedev and Fable.Elmish.Debugger working for you? cc @MangelMaxime

**Comment by MangelMaxime** [comment]
I saw no problem on my side.

Is the update recent ?

**Comment by alfonsogarciacaro** [comment]
Hmm, I think I messed it up. It's the `redux-devtools` which has been updated recently, but the `remotedev` package is still quite old. I'm not getting security warnings from `npm audit` anymore though. Weird... 🤔

**Comment by alfonsogarciacaro** [comment]
I was actually having [this issue](https://twitter.com/grishace/status/1067853259627421696) and it seems it's [fixed now](https://twitter.com/mdiordiev/status/1067859792704798720) :tada:

**Comment by zalmoxisus** [comment]
This issue should be fixed in https://github.com/zalmoxisus/remotedev/pull/13, which was just published in `0.2.8`. Sorry about the delay!

**Comment by et1975** [comment]
Thanks Mihail!
