### ISSUE TITLE
when replay from redux tools incorrect serialization of list

### ISSUE THREAD

**Issue by OnurGumus** [elmish/debugger#13]
### Description

I have noticed that when replying from redux tools, it sends an array, and elmish debugger doesn't even check what type it is serializing. if target type is a list, instead it gives an empty list.

### Repro code

Create a model with a list more than one elements, and console log list length in your view function. Then replay some state from redux tools. 

### Expected and actual results
Expected  : List should be reconstructed
Please provide the expected and actual results.
Actual : We get an empty list 
### Related information 

* fable-compiler version: 2.0.4

**Comment by MangelMaxime** [comment]
We probably need to implements a function `inflate` that's use reflection over `'model` to detect when there is a list and re-build it from the array reprensation.

[Related place](https://github.com/elmish/debugger/blob/master/src/debugger.fs#L73-L77)

**Comment by et1975** [comment]
@OnurGumus thanks for the report!
Could you give an example of the state model causing this issue?

**Comment by OnurGumus** [comment]
This is my model

```fs
type Time = int list
type Status =
    | Initial
    | JustStarted
    | Complete
    | Wrong
    | Correct

type Message = 
    | Tick
    | StartOver
    | KeyPress
    | TextUpdated of string

type TypingModel = { Time : Time; Status : Status; CurrentText : string; TargetText : string }
```

This is how initialized =

```fs

let init () =
    { Status = Initial; 
        CurrentText = ""; 
        TargetText = ""; 
        Time =[0;0;0;0] }, Cmd.none
```
And this is the view

```fs
let root model dispatch =
     console.log(model)

     div [][]
```

**Comment by alfonsogarciacaro** [comment]
I think we'll have to use something like Thoth.Json for proper (de)serialization with Fable 2, there's some discussion [here](https://github.com/elmish/debugger/issues/10#issue-346563450).

**Comment by et1975** [comment]
Yes, shouldn't be a problem. Just have to figure out where it's OK to instantiate the generated serializer (wrt. generics and Fable limitations).

**Comment by alfonsogarciacaro** [comment]
As all the entry functions are inlined, this shouldn't be a problem. I made a tentative PR #14 but I haven't tested it yet.

**Comment by OnurGumus** [comment]
2.0.1 works for properly now. Thanks.
