### ISSUE TITLE
Influence Message / State formatting

### ISSUE THREAD

**Issue by 0x53A** [elmish/debugger#18]
Is there a way to influence how messages / models are printed?

At the moment, all the information is there, but you need to click down a lot until you see anything usefull:

![grafik](https://user-images.githubusercontent.com/4236651/48717917-a0730f00-ec1a-11e8-83bc-ad48679dd452.png)

**Comment by MangelMaxime** [comment]
When using the redux extension you `pin` your message and model to a specific point so the next states will be shown as pinned. 

This is something related to the redux extension not something we can influence from our side I think. We are only sending the JSON data.

**Comment by 0x53A** [comment]
I haven't yet done any native typescript react redux project.

But if you compare it with Fable-Redux at http://fable.io/samples-browser/redux-todomvc/

![grafik](https://user-images.githubusercontent.com/4236651/48718617-07dd8e80-ec1c-11e8-8f71-3973ac948a7e.png)

Afaik in Redux, you don't have one toplevel message type where everything is wrapped, instead you have different toplevel message types.

Where in a Fable Elmish project everything is a ``UserMsg``, in a Redux project, the message types are ``CompleteAll``, ``ClearCompleted``, ``AddTodo``, ...

That maybe makes it a bit easier to see what happens at a glance.

**Comment by 0x53A** [comment]
This would need small changes in core elmish, but it would be nice if we could inject the debugger into the dispatch mappings here:

https://github.com/SAFE-Stack/SAFE-BookStore/blob/69cd5a226f560c683c4a58bd473b4e48b197a158/src/Client/Shared.fs#L32-L42

If the debugger had hooks in ``Cmd.map`` and a new ``Dispatch.map``, then it would be able to show the original inner msg, not the outer msg.

**Comment by 0x53A** [comment]
But you answered my question, and I found the ``pin`` you mentioned, which is usefull, thanks.

In my experience, *It Would Be Nice If Someone (else) Did Something* almost never happens, so I will think about the debugger hooks and dispatch etc a bit and maybe open an issue/pr at core elmish ;)

Thank you!

**Comment by et1975** [comment]
You are comparing apples and oranges, compare Todo to Todo and the messages
should look about the same.
