### ISSUE TITLE
Please publish on nuget v3.0.0

### ISSUE THREAD

**Issue by rfrerebe** [elmish/debugger#27]
### Description

v3.0.0 version is commited in repo, but missing in nuget.
Could you please publish it to nuget ?

### Expected and actual results
See v3.0.0 on [https://www.nuget.org/packages/fable.elmish.debugger](https://www.nuget.org/packages/fable.elmish.debugger)

Currently latest stable is 2.0.3

![image](https://user-images.githubusercontent.com/12632865/56576631-31cf1e80-65c9-11e9-905b-7b27b0485b0d.png)

**Comment by et1975** [comment]
Sorry, missed the nuget publish step, but I think we need to wait for https://github.com/elmish/debugger/pull/26 now.

**Comment by et1975** [comment]
Published!
