### ISSUE TITLE
Elmish debugger can't work with decimal

### ISSUE THREAD

**Issue by forki** [elmish/debugger#30]
[ELMISH DEBUGGER] Cannot generate auto encoder for System.Decimal. Please pass an extra encoder.

I think this error is rooted at:

![image](https://user-images.githubusercontent.com/57396/57454842-0fe0c780-726a-11e9-8507-872939cbcda8.png)

**Comment by alfonsogarciacaro** [comment]
Yes, you need to pass custom inflater/deflater with the additional decoder. We should provide an easy way to do that, but with latest version you can do it as follows:

```fsharp
open Elmish
open Elmish.Debug
open Thoth.Json

#if DEBUG
// Add here the coders you need, this may be already available somewhere in your app
let additionalCoders =
    Extra.empty
    |> Extra.withInt64
    |> Extra.withDecimal

let inline getDebuggerHelpers<'Msg, 'Model>() =
    let connection = Debugger.connect<'Msg> Debugger.ViaExtension
    let deflater =
        let enc = Encode.Auto.generateEncoderCached<'Model>(extra = additionalCoders)
        fun x ->
            try enc x
            with er ->
                JS.console.warn("[ELMISH DEBUGGER]", er.Message)
                box x
    let inflater =
        let decoder = Decode.Auto.generateDecoderCached<'Model>(extra = additionalCoders)
        fun (x: obj) ->
            match Decode.fromValue "$" decoder x with
            | Ok x -> x
            | Error er ->
                JS.console.warn("[ELMISH DEBUGGER]", er)
                x :?> _
    deflater, inflater, connection

// Build the helpers with your types
let deflater, inflater, connection = getDebuggerHelpers<MyMsg, MyModel>()
#endif

// Start the app
Program.mkSimple init update view
|> Program.withReactSynchronous "main-app"
#if DEBUG
|> Program.withDebuggerUsing deflater inflater connection
|> Program.withConsoleTrace
#endif
|> Program.run
```

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Can we "just" create another version of `withDebuggerUsing` which accept `additionalCoders` to pass to `Thoth.Json.Auto.xxx`?

Or is there something more complex to handle?

**Comment by vbfox** [comment]
Maybe also by default add all additional ones provided by Thoth ?

It's already a debug functionality doing auto-magical json serialization, it can do it with all in-the-box serializers and I don't think if this is enabled there is any size/treeshaking consideration

**Comment by alfonsogarciacaro** [comment]
> Can we "just" create another version of withDebuggerUsing which accept additionalCoders to pass to Thoth.Json.Auto.xxx?

That was my first idea, but I'm in doubt if it's better/more flexible to pass directly the Thoth encoder/decoder.

> Maybe also by default add all additional ones provided by Thoth ?

You're right, given that most users will disable the debugger in production we could use the additional coders directly.

My main concern is some users may forget to use the `#if DEBUG` directive. I've wondered sometimes if Elmish.Debugger should implement `#if DEBUG` directly and do nothing in production [as Elmish.HMR does](https://github.com/elmish/hmr/blob/8e5263451c8f23c069377e5c1de6d52235542268/src/hmr.fs#L196-L201). Although some users may want to use the debugger in production too 😕 What do you think @et1975?

**Comment by et1975** [comment]
I see instances where apps run with the debugger in production (slack,
office365). I think we should include all the serializers we have, but
leave it to the user to decide if the debugger should be enabled. If the
user decided to run it in production they have the option to provide custom
serializers.

**Comment by forki** [comment]
Awesome. Thanks

Alfonso Garcia-Caro <notifications@github.com> schrieb am So., 12. Mai
2019, 23:50:
