### ISSUE TITLE
Can't use debugger on non JS application

### ISSUE THREAD

**Issue by fdbeirao** [elmish/debugger#32]
### Description

I have a console application. It doesn't use Fable. It doesn't have a UI at all.
I would like to be able to use ` |> Program.withDebugger` or even `|> Program.withDebuggerAt (Debugger.Remote("localhost", 8000))` but when I try to start the app, I immediately get an exception on `Program.withDebugger`:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for '<StartupCode$Fable-Core>.$Fable.Core.JS' threw an exception.
  Source=Fable.Elmish.Debugger
  StackTrace:
   at Elmish.Debug.Debugger.showError(FSharpList`1 msgs)
   at Program.main(String[] argv) in Program.fs:line 20

Inner Exception 1:
Exception: JS only
```

### Repro code

Brand new F# Console Application (Visual Studio 2019). This is the code in `Program.fs`:

```fsharp
open Elmish
open Elmish.Debug

type Model = int

type Msg = NoOp

let init _ =
    0, Cmd.none

let update msg model =
    model, Cmd.none

let view _ _ = 
    ignore

[<EntryPoint>]
let main argv =
    do Program.mkProgram init update view
    |> Program.withDebuggerAt (Debugger.Remote("localhost", 8000))
    |> Program.run 
    
    0
```

### Expected and actual results

I expect to be able to use a time travel debugger in a desktop (non fable, non browser) Elmish application. I expect not to get an exception 😅 As stated in [the docs](https://elmish.github.io/debugger/): `Whether you target browser, native or any other platform, as long as you can connect to a monitor you can start collecting and visualizing the events.`

### Related information 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Elmish" Version="3.0.3" />
    <PackageReference Include="Fable.Elmish.Debugger" Version="3.0.2" />
  </ItemGroup>
</Project>
```

* fable-compiler version: ??
* fable-core version: ??
* Operating system: Windows 10 Pro x64 Version 1809, OS Build 17763.504

**Comment by MangelMaxime** [comment]
`Fable.Elmish.Debugger` only works for JavaScript runtime this is why we prefix it using `Fable`.

Here you are targeting .Net runtime.

**Comment by fdbeirao** [comment]
So, how do I accomplish the promise from the docs: `Whether you target browser, native or any other platform, as long as you can connect to a monitor you can start collecting and visualizing the events.` ? Or am I interpreting it wrong?
Is there a different package I need?

**Comment by MangelMaxime** [comment]
The statement is not really clear but what it means is that. [Redux dev tools](https://github.com/reduxjs/redux-devtools) can be used for any Elmish project as long as you are able to provide a way to connect to the Redux dev tools monitor.

However the library `Fable.Elmish.Debugger` is JS runtime only

**Comment by fdbeirao** [comment]
So I guess I can't really use what I want. That's a shame, but also perhaps a good opportunity to contributing to open source. To me it would make total sense to not depend on JS. 🙏🏻 cheers and thank you for your answers @MangelMaxime

**Comment by MangelMaxime** [comment]
Well, Elmish is JavaScript centric at first and Redux dev tools have been created for React so ^^

But I think Redux dev tools, is using the HTTP protocol to communicate so in theory it should be possible for you to write your own connector for it.

**Comment by et1975** [comment]
Yes, we need a TCP-based transport, see #7
