### ISSUE TITLE
Thoth.Json version range too wide

### ISSUE THREAD

**Issue by WalternativE** [elmish/debugger#38]
### Description

The allowed version range of `Thoth.Json` is currently >=3.0.0. Projects using e.g. `Thoth.Json` 3.4.1 will encounter compiler errors when building a project using the Elmish Debugger with the .NET Core SDK `dotnet build` command.

### Repro code

[This repository](https://github.com/WalternativE/ElmishDebuggerThothJsonClash) contains a working repro of the issue. The Fable Compiler appears to work, FSC included in the .NET Core SDK (tested for versions >= 3.0.100 including the newest previews) will fail.

### Expected and actual results

__Expected:__
Dependencies within the version range should not cause failures

__Actual:__
A dependency within the version range causes a build failure.

__Extra:__
I assume this is just me, not having the full picture. Paying closer attention to the template projects I saw that Fable projects are virtually never compiled with the .NET Core SDK and always via the Fable Compile using the webpack loader. I just stumbled upon this failure because I didn't use the templates and manually added the project to the `.sln` which caused it to have a build target. Is this behavior expected for the 'normal' Fable setup?

### Related information 

* elmish version: 3.0.6
* fable-compiler version: 2.4.7
* fable-core version: 3.1.3
* Operating system: Windows 10 1909

**Comment by MangelMaxime** [comment]
I think we could release a new version of `Elmish.Debugger` which request for `Thoth.Json >= 3.4.1`.

The `3.4.1` API doesn't contain breaking change in the API. It just contains internal changes and I think `dotnet` is not figuring out everything by itself... For example, I had to re-package a new version of all my packages which use `Thoth.Json.Net` just to make `dotnet` happy while no breaking change existed.

**Comment by WalternativE** [comment]
That should work fine I suppose. Should the new version reflect the change in its version somehow? Like, it doesn't really introduce a breaking change, the SDK just breaks in some instances.

**Comment by MangelMaxime** [comment]
Could just bump the `Y` in `X.Y.Z` version.

**Comment by WalternativE** [comment]
Should be enough yeah. Maybe it would also be sensible to have a patch release (3.0.4 perhaps) that constrains `Thoth.Json` to <= 3.1.0. I' not 100% sure if this is needed though (or if it helps). Unfortunately most templates use something in the direction of `Thoth.Json ~> 3` - at least paket will make noise about the versions. Am I too paranoid about this?

**Comment by MangelMaxime** [comment]
Can you please try version `3.1.0-beta-1`?

I am not really getting the noise thing. If you use `Thoth.Json ~> 3` it will upgrade to `3.1.0` because the version is in range so that's fine.

**Comment by WalternativE** [comment]
Works like a charm! 🙏

**Comment by sashang** [comment]
Just a question. I've run into this issue on Linux, and downgrading Thoth.Json to 3.1.0 resolves the error. Is it planned to to be fixed for Thoth.Json 3.4 so I don't have to pin it to 3.1.0?

**Comment by MangelMaxime** [comment]
I released version 3.1.0 stable it should work out the box now.
