### ISSUE TITLE
Time-travelling doesn't work

### ISSUE THREAD

**Issue by et1975** [elmish/debugger#6]
React SPA doesn't redraw the state. The state is passed in by the Chrome extension, but is not rendered. Fails in every app I tried.
Would be great If someone could confirm if that's not my local issue.

Investigating in the meantime...

**Comment by MangelMaxime** [comment]
For me its working with Firefox `Redux DevTools 2.15.3` and this version of dependencies:

```
STORAGE: NONE
RESTRICTION: == netstandard2.0
NUGET
  remote: https://www.nuget.org/api/v2
    Fable.Core (1.3.17)
      FSharp.Core (>= 4.2.3)
      NETStandard.Library (>= 1.6.1)
    Fable.Elmish (1.0.3)
      Fable.Core (>= 1.3.8)
      Fable.PowerPack (>= 1.3.4)
      FSharp.Core (>= 4.2.3)
    Fable.Elmish.Browser (1.0)
      Fable.Core (>= 1.2.4)
      Fable.Elmish (>= 1.0)
      Fable.Import.Browser (>= 0.1)
      FSharp.Core (>= 4.2.3)
    Fable.Elmish.Debugger (1.0.1)
      Fable.Core (>= 1.3.1)
      Fable.Elmish (>= 1.0)
      FSharp.Core (>= 4.2.3)
    Fable.Elmish.HMR (1.0)
      Fable.Core (>= 1.2.4)
      Fable.Elmish (>= 0.9.2)
      FSharp.Core (>= 4.2.3)
    Fable.Elmish.React (1.0.3)
      Fable.Core (>= 1.3.8)
      Fable.Elmish (>= 1.0.1)
      Fable.PowerPack (>= 1.3.2)
      Fable.React (>= 2.0)
      FSharp.Core (>= 4.2.3)
    Fable.Import.Browser (1.1.2)
      Fable.Core (>= 1.3.8)
    Fable.PowerPack (1.5)
      Fable.Core (>= 1.3.8)
      Fable.Import.Browser (>= 1.0)
      FSharp.Core (>= 4.2.3)
    Fable.React (3.1.2)
      Fable.Core (>= 1.3.12)
      Fable.Import.Browser (>= 1.1.1)
    FSharp.Core (4.3.4) - redirects: force
    Fulma (1.0.0-beta-019)
      Fable.Core (>= 1.3.12)
      Fable.React (>= 3.1)
    Microsoft.NETCore.Platforms (2.0.2)
    NETStandard.Library (2.0.3)
      Microsoft.NETCore.Platforms (>= 1.1)
```

I directly tested it from Fulma minimal template.

**Comment by et1975** [comment]
Haven't used this in a while and forgot that the debugger has to be added after react:
```
|> Program.withReact "elmish-app"
|> Program.withDebugger
```

We'll have to address this ordering problem.

**Comment by MangelMaxime** [comment]
We discussed it in the past and didn't find a nice solution to this problem.

However I don't remember if we discussed it in Elmish repo or in the SAFE stack.

**Comment by et1975** [comment]
I remember, I actually have one solution in mind: CE that can rearrange the order, based on some precedence attribute. I have a feeling there might be a better one though (like getting rid of `Program` entirely), but that would be a big rewrite.
