### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nojaf** [elmish/debugger#9]
### Description

Getting a maximum call stack size exceeded error when triggering a simple message.

![image](https://user-images.githubusercontent.com/2621499/42218084-bc9b4ca8-7ec7-11e8-8a27-23192d94f9f7.png)

### Repro code

```fsharp
module App.View

open Elmish
open Fable.Helpers.React
open Fable.Helpers.React.Props
open Fulma
open Fulma.FontAwesome
open Fable.Core
open Fable.Core.JsInterop



type Model =
    { Value : string }

type Msg =
    | MapClick of obj

let init _ = { Value = "" }, Cmd.none

let private update msg model =
    match msg with
    | MapClick latLng ->
        { model with Value = sprintf "%A" latLng }, Cmd.none

let private view model dispatch =
    printfn "view"
    div [] [
        p [] [str model.Value]
        button [OnClick (box >> Msg.MapClick >> dispatch)] [str "click"]
    ]

open Elmish.React
open Elmish.Debug
open Elmish.HMR

Program.mkProgram init update view
#if DEBUG
|> Program.withHMR
#endif
|> Program.withReactUnoptimized "elmish-app"
#if DEBUG
|> Program.withDebugger // Code works when this line is commented.
#endif
|> Program.run

```

### Expected and actual results

When clicking the button, the error is triggered.

### Related information 

* elmish version: 1.0.3
* fable-compiler version: 1.3.17
* fable-core version: 1.3.17
* Operating system: Windows

Project was create with the [Fulma template](https://mangelmaxime.github.io/Fulma/#template)

**Comment by MangelMaxime** [comment]
The object you are passing is too big for stringifying it.

Same thing will probably occured if you do `JSON.stringify yourClickEv`

You should pass only the data you need.

When, you use a form input you pass: 
```fs
OnInput (fun ev -> MyMsg ev.Value)
``` 
not:
```fs
OnInput (fun ev -> MyMsg ev)
```

**Comment by alfonsogarciacaro** [comment]
I have helpers like these in my project, maybe we could add them to Fable.React to prevent these situations:

```fsharp
let inline onValueChanged f =
    OnChange (fun ev -> (ev.target :?> Browser.HTMLInputElement).value |> f)

let inline onChecked f =
    OnChange (fun ev -> (ev.target :?> Browser.HTMLInputElement).``checked`` |> f)
```

**Comment by et1975** [comment]
This might actually work w/o a debugger and tracing, but as @MangelMaxime said, for showing the debug info we serialize the messages and in case of the full event object it will drag the entire browser DOM along. Closing.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro  Hum for the first one we already added `ev.Value` for this specific case.

https://github.com/fable-compiler/fable-react/blob/master/src/Fable.React/Fable.Helpers.React.fs#L1096-L1100

**Comment by nojaf** [comment]
Could we not improve the error message? If you don't know this, it's hard to figure out...

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Oh, I didn't know about that 😮 😅 

@nojaf It's difficult to detect this kind of errors, I myself have been bitten by them several times. I think the main problem is we (by "we" I mean "I") started to use dynamic operators when dealing with React events (`OnClick (fun ev -> ev.target?value |> doSomething)`)  which makes it easy to just write `ev?value` (or box in your case) and the compiler won't complain. We need to get used to write `(ev.target :?> Browser.HTMLInputElement).value` or use extensions like the one Maxime pointed out.
